stages:
  - build
  - get
  - deploy
  - run

kill_whatsbot:
  stage: build
  script:
    - killall whatsbot
  allow_failure: true

kill_python:
  stage: build
  script:
    - killall python
  allow_failure: true

delete_old:
  stage: build
  script:
    - rm -rf whatsapp-bot
  allow_failure: true

clone:
  stage: get
  script:
    - git clone http://gitlab.namibsun.net/namboy94/whatsapp-bot.git
    - python whatsapp-bot/whatsbot/main.py -i

write_script:
  stage: deploy
  script:
    - touch whatsapp-bot/runner
    - echo "while true" >> whatsapp-bot/runner
    - echo "do" >> whatsapp-bot/runner
    - echo "$HOME/whatsapp-bot/whatsbot/main.py" >> whatsapp-bot/runner
    - echo "done" >> whatsapp-bot/runner

startbot:
  stage: run
  script:
    - whatsapp-bot/runner&
