stages:
  - clean
  - get
  - upload
  - upgrade
  - deploy

kill_whatsbot:
  stage: clean
  script:
    - killall whatsbot
  allow_failure: true

kill_whatsbot_instance:
  stage: clean
  script:
    - killall whatsbot-instance
  allow_failure: true

delete_old:
  stage: clean
  script:
    - cd
    - rm -rf whatsapp-bot
  allow_failure: true

clone:
  stage: get
  script:
    - cd
    - git clone http://gitlab.namibsun.net/namboy94/whatsapp-bot.git

upload_to_pypi:
  stage: upload
  script:
    - cd
    - cd whatsapp-bot
    - python setup.py register sdist upload
    - sleep 60
  allow_failure: true

upgrade_from_pypi:
  stage: upgrade
  script:
    - sudo pip3.5 install whatsbot --upgrade
    - sleep 5

startbot:
  stage: deploy
  script:
    - nohup whatsbot &
    - exit 0
