stages:
  - setup
  - test
  - upload
  - cleanup
  - upgrade

clone:
  stage: setup
  script:
    - cd
    - git clone http://gitlab.namibsun.net/namboy94/messengerbot.git
    - git clone git@gitlab.namibsun.net:namboy94/messengerbot.wiki.git
    - cd messengerbot
    - git push -u git@gitlab.com:namboy94/messengerbot.git --all
    - git push -u git@github.com:namboy94/messengerbot.git --all
    - git push -u git@bitbucket.org:namboy94/messengerbot.git --all

uninstall:
  stage: setup
  only:
    - master
  script:
    - sudo pip3.5 uninstall -y messenger_bot
  allow_failure: true

run_unit_tests:
  stage: test
  only:
    - master
    - develop
    - unit-test
  script:
    - cd
    - cd messengerbot
    - python setup.py test
  allow_failure: true

generate_statistics:
  stage: test
  only:
    - master
  script:
    - cd
    - cd messengerbot
    - git_stats generate
    - cd
    - cd messengerbot.wiki
    - cp -r ../messengerbot/git_stats .

generate_documentation:
  stage: test
  only:
    - master
  script:
    - cd
    - cd messengerbot/doc
    - make clean
    - make buildsource
    - make html
    - cd
    - cd messengerbot.wiki
    - rm -rf html
    - cp -r ../messengerbot/doc/build/html .

upload_to_pypi:
  stage: upload
  only:
    - master
  script:
    - cd
    - cd messengerbot
    - python setup.py register sdist upload
    - sleep 60
  allow_failure: true

upload_documentation_and_statistics:
  stage: upload
  only:
    - master
  script:
    - cd
    - cd messengerbot.wiki
    - git add --all
    - git commit -m "Updated documentation and statistics"
    - git push -u origin master

delete_clone:
  stage: cleanup
  when: always
  script:
    - cd
    - rm -rf messengerbot
    - rm -rf messengerbot.wiki

upgrade_from_pypi:
  stage: upgrade
  when: always
  only:
    - master
  script:
    - sudo pip3.5 install messenger_bot --upgrade
    - sleep 5