stages:
  - setup
  - test
  - upload
  - cleanup
  - upgrade

clone:
  stage: setup
  script:
    - cd
    - git clone http://gitlab.namibsun.net/namboy94/whatsapp-bot.git

run_unit_tests:
  stage: test
  script:
    - cd
    - cd whatsapp-bot
    - python setup.py test

upload_to_pypi:
  stage: upload
  script:
    - cd
    - cd whatsapp-bot
    - python setup.py register sdist upload
    - sleep 60
  allow_failure: true

delete_clone:
  stage: cleanup
  script:
    - cd
    - rm -rf whatsapp-bot

upgrade_from_pypi:
  stage: upgrade
  script:
    - sudo pip3.5 install whatsbot --upgrade
    - sleep 5
