stages:
  - setup
  - test
  - deploy
  - wiki

mirror_repo:
  stage: setup
  only:
    - master
    - develop
  script:
    #- git push -u git@gitlab.com:namboy94/messengerbot.git --all
    - git push -u git@github.com:namboy94/messengerbot.git --all
    #- git push -u git@bitbucket.org:namboy94/messengerbot.git --all

run_unit_tests:
  stage: test
  only:
    - master
    - develop
  script:
    - python3 setup.py test

upload_to_pypi:
  stage: deploy
  only:
    - master
  script:
    - python3 setup.py register sdist upload
  allow_failure: true

upload_documentation_and_statistics:
  stage: wiki
  only:
    - master
  script:
    - git_stats generate
    - cd doc
    - make clean
    - make buildsource
    - make html
    - cd ..

    - git clone git@gitlab.namibsun.net:namboy94/messengerbot.wiki.git
    - cd messengerbot.wiki
    - rm -rf git_stats html
    - mv ../git_stats .
    - mv ../doc/build/html .
