stages:
  - build
  - get
  - predeploy
  - run

kill_whatsbot:
  stage: build
  script:
    - killall whatsbot
  allow_failure: true

kill_python:
  stage: build
  script:
    - killall python
  allow_failure: true

delete_old:
  stage: build
  script:
    - cd
    - rm -rf whatsapp-bot
  allow_failure: true

clone:
  stage: get
  script:
    - cd
    - git clone http://gitlab.namibsun.net/namboy94/whatsapp-bot.git
    - python whatsapp-bot/whatsbot/main.py -i

write_script:
  stage: predeploy
  script:
    - cd
    - touch runner
    - echo "while true" >> runner
    - echo "do" >> runner
    - echo "python $HOME/whatsapp-bot/whatsbot/main.py" >> runner
    - echo "done" >> runner

startbot:
  stage: deploy
  script:
    - cd
    - bash runner&
    - exit 0
